/** @copyright Copyright © 2026 GUIHO Technologies as represented by Cristóvão GUIHO. All Rights Reserved. */

export { CATEGORY_MAP, CATEGORIES, CATEGORY_ORDER };

const CATEGORY_MAP: Record<string, string> = {
  "app-shell": "Layout",
  "aspect-ratio": "Layout",
  center: "Layout",
  container: "Layout",
  flex: "Layout",
  grid: "Layout",
  group: "Layout",
  "simple-grid": "Layout",
  space: "Layout",
  stack: "Layout",
  "alpha-slider": "Inputs",
  "angle-slider": "Inputs",
  checkbox: "Inputs",
  chip: "Inputs",
  "color-input": "Inputs",
  "color-picker": "Inputs",
  fieldset: "Inputs",
  "file-input": "Inputs",
  "hue-slider": "Inputs",
  input: "Inputs",
  "json-input": "Inputs",
  "mask-input": "Inputs",
  "native-select": "Inputs",
  "number-input": "Inputs",
  "password-input": "Inputs",
  "pin-input": "Inputs",
  radio: "Inputs",
  "range-slider": "Inputs",
  rating: "Inputs",
  "segmented-control": "Inputs",
  slider: "Inputs",
  switch: "Inputs",
  textarea: "Inputs",
  "text-input": "Inputs",
  autocomplete: "Combobox",
  combobox: "Combobox",
  "multi-select": "Combobox",
  pill: "Combobox",
  "pills-input": "Combobox",
  select: "Combobox",
  "tags-input": "Combobox",
  "tree-select": "Combobox",
  "action-icon": "Buttons",
  button: "Buttons",
  "close-button": "Buttons",
  "copy-button": "Buttons",
  "file-button": "Buttons",
  "unstyled-button": "Buttons",
  anchor: "Navigation",
  breadcrumbs: "Navigation",
  burger: "Navigation",
  "nav-link": "Navigation",
  pagination: "Navigation",
  stepper: "Navigation",
  "table-of-contents": "Navigation",
  tabs: "Navigation",
  tree: "Navigation",
  alert: "Feedback",
  loader: "Feedback",
  notification: "Feedback",
  progress: "Feedback",
  "ring-progress": "Feedback",
  "semi-circle-progress": "Feedback",
  skeleton: "Feedback",
  affix: "Overlays",
  dialog: "Overlays",
  drawer: "Overlays",
  "floating-indicator": "Overlays",
  "floating-window": "Overlays",
  "hover-card": "Overlays",
  "loading-overlay": "Overlays",
  menu: "Overlays",
  modal: "Overlays",
  overlay: "Overlays",
  popover: "Overlays",
  tooltip: "Overlays",
  accordion: "Data Display",
  avatar: "Data Display",
  "background-image": "Data Display",
  badge: "Data Display",
  card: "Data Display",
  "color-swatch": "Data Display",
  image: "Data Display",
  indicator: "Data Display",
  kbd: "Data Display",
  "number-formatter": "Data Display",
  "overflow-list": "Data Display",
  "rolling-number": "Data Display",
  spoiler: "Data Display",
  "theme-icon": "Data Display",
  timeline: "Data Display",
  blockquote: "Typography",
  code: "Typography",
  highlight: "Typography",
  list: "Typography",
  mark: "Typography",
  table: "Typography",
  text: "Typography",
  title: "Typography",
  typography: "Typography",
  box: "Miscellaneous",
  collapse: "Miscellaneous",
  divider: "Miscellaneous",
  "focus-trap": "Miscellaneous",
  marquee: "Miscellaneous",
  paper: "Miscellaneous",
  portal: "Miscellaneous",
  "scroll-area": "Miscellaneous",
  scroller: "Miscellaneous",
  transition: "Miscellaneous",
  "visually-hidden": "Miscellaneous",
};

const CATEGORIES: string[] = [
  "Layout",
  "Inputs",
  "Combobox",
  "Buttons",
  "Navigation",
  "Feedback",
  "Overlays",
  "Data Display",
  "Typography",
  "Miscellaneous",
];

const CATEGORY_ORDER: Record<string, number> = {};
CATEGORIES.forEach((c, i) => {
  CATEGORY_ORDER[c] = i;
});
